# ===============================
# DATABASE
# ===============================

db.driver=com.mysql.cj.jdbc.Driver
db.url=${DB_URL:jdbc:mysql://localhost:3306/vistadbv4}
db.username=${DB_USERNAME:root}
db.password=${DB_PASSWORD:12345678}

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:your_super_secret_jwt_key}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# CLOUDINARY
# ===============================

cloudinary.cloud_name=${CLOUDINARY_NAME:your_cloud_name}
cloudinary.api_key=${CLOUDINARY_KEY:your_api_key}
cloudinary.api_secret=${CLOUDINARY_SECRET:your_api_secret}