
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


categories.page_size=20
provider.page_size=20
services.page_size=15
cart.page_size=15
order.page_size=10