# ===============================
# DATABASE
# ===============================

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=${HIBERNATE_SHOW_SQL:true}
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver

hibernate.connection.url=${DB_URL:jdbc:mysql://localhost:3306/vistadbv4}
hibernate.connection.username=${DB_USERNAME:root}
hibernate.connection.password=${DB_PASSWORD:12345678}


# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:jVistaaTravelZuncuteihhruihnqZuncute196@oiqu93873i$$@61*9@&!(u3JAdjbJBDHABDIHYUWoejwiuiih@451}
jwt.expiration=${JWT_EXPIRATION:86400000}


# ===============================
# CLOUDINARY
# ===============================

cloudinary.cloud_name=${CLOUDINARY_NAME:dgq228v63}
cloudinary.api_key=${CLOUDINARY_KEY:751113235194963}
cloudinary.api_secret=${CLOUDINARY_SECRET:ynQDfyqgC6BuNoaNY9ytxwtRhIs}